version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: meetamjadsaeed
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: task_manager
      POSTGRES_HOST: db
      REDIS_ADDR: redis:6379
      JWT_SECRET: yourjwtsecret
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: meetamjadsaeed
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
